version: '2.1'
orbs:
  node: circleci/node@5.0.2
jobs:
  test:
    executor:
      name: node/default
      tag: '13.14'
    steps:
      - checkout
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - run: sudo npm install -g npm@latest
      - run: npm run test

workflows:
  test_api:
    jobs:
      - test
